version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - 5231:5231
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQLSERVER_CONNECTION_STRING=Server=db;Database=MovieWatchList;User=sa;Password=Your_password123;
      - TMDB_API_KEY=your_tmdb_api_key
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
